### ISSUE TITLE
Display the feed URL in the "Datastream Endpoint" field of the Paid page

### ISSUE THREAD

**Issue by kitblake** [chaineresearch/datastreams#10]
Currently when a Consumer procures a streaming asset the "Datastream Endpoint" field in the Paid page contains the hash of the encrypted URL. This should just be the URL in clear text.

Ref: https://htmlpreview.github.io/?https://github.com/chaineresearch/assets/blob/main/market_mockups/paid.html

**Comment by kitblake** [comment]
This is working nicely. 

Hey @okpoEkpenyong, how can I adjust the style of the elements? Can I add a CSS class to, say, the input field that contains the endpoint URL? Right now it's just default but there are existing classes that could be applied.

**Comment by kitblake** [comment]
To be clear, I'd like to do this myself :) But I'd need you to show me where it lives in the code.

**Comment by okpoEkpenyong** [comment]
Hey @kitblake. We will set up a time to do that.
