### ISSUE TITLE
Public datastream asset pages include an erroneous link to Sample Data

### ISSUE THREAD

**Issue by kitblake** [chaineresearch/datastreams#18]
When a Datastream asset gets published the view page includes a "Sample Data" element with a "Download Sample" link that links to the API docs. This entire element doesn't apply and needs to be removed.

**Comment by okpoEkpenyong** [comment]
Thanks for pointing out. Done.

**Comment by kitblake** [comment]
As seen in the meeting screenshare, this is fixed. 
Closing.
