### ISSUE TITLE
Datastream Endpoint field needs to be copyable

### ISSUE THREAD

**Issue by kitblake** [chaineresearch/datastreams#19]
In the Paid page the "Copy Feed URL" button is working nicely and copies the URL. The Datastream Endpoint field needs to be copyable too. Currently if you copy the URL in the field you get the ellipsis, as in:
https://real…le-positions/v2/hsl

Ideally the entire URL content of the field would select – e.g. this.select(); – when the field gets cursor focus. This saves a step for the user.

**Comment by okpoEkpenyong** [comment]
Why do we need to copy from two places? Wouldn't this be a repetition?. Pls, Let the datastream endpoint box be for display alone.

**Comment by okpoEkpenyong** [comment]
Let the datastream endpoint box be for display alone.

**Comment by kitblake** [comment]
As it's an input field, it looks like it'll be copyable. But let's let it go for now. 
Adding the "Won't fix" label and closing.
