### ISSUE TITLE
Add the "still in testing" warning to the publish/1 form

### ISSUE THREAD

**Issue by kitblake** [chaineresearch/datastreams#20]
When creating an Algorithm a warning appears. In an earlier version we had: "Datastream is still in a testing phase, please use it only on test networks." As the Datastream asset is definitely still in testing it would be wise to restore that element.

**Comment by okpoEkpenyong** [comment]
Done. Merging now

**Comment by kitblake** [comment]
Looks nice and professional. 
Closing.
