### ISSUE TITLE
Make the user land in the "Stream" tab on the 'Access' subform if "Data Stream" was chosen on the 'Metadata' subform

### ISSUE THREAD

**Issue by sarvagyaa** [chaineresearch/datastreams#7]
If we choose "Data Stream" in the 'Metadata' sub-page can we make sure that "Stream" is chosen already when we continue to the 'Access' sub-page?   

When we choose, "Dataset" in 'Metadata', "Download" is already chosen in 'Access'. And when we choose "Algorithm" in 'Metadata', the "Compute" sub-page loads in 'Access', but there are no tabs (buttons) on top. This behaviour is same as in the Ocean Market in prod.

**Comment by sarvagyaa** [comment]
Kit: That would be not only user-friendly but would prevent mis-submissions where the Publisher fills in the wrong subform.

**Comment by sarvagyaa** [comment]
This still doesn't work on the Netlify instance.

**Comment by okpoEkpenyong** [comment]
We will tackle this later. For now let's make do with the Box selection.
